app/src/main/java/com/tanasi/streamflix/providers/AnimeWorldProvider.kt
app/src/main/java/com/tanasi/streamflix/providers/Provider.kt

feat: Create AnimeWorld provider (IT)

---

.gitignore
app/build.gradle
app/src/main/java/com/tanasi/streamflix/extractors/VoeExtractor.kt
build.gradle
navigation/build.gradle
retrofit-jsoup-converter/build.gradle

Hi! Long time no see.
I fixed an extractor and updated all dependencies along side.
I tested it with my local emulator.
This fixes the following comment issue: https://github.com/stantanasi/streamflix/issues/219#issuecomment-2466922389

fix(extractors): update VOE and upgrade dependencies

---

app/build.gradle
app/src/main/java/com/tanasi/streamflix/extractors/Extractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/MStreamClickExtractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/MStreamDayExtractor.kt
app/src/main/java/com/tanasi/streamflix/providers/MStream.kt
app/src/main/java/com/tanasi/streamflix/providers/MStreamProvider.kt
app/src/main/java/com/tanasi/streamflix/providers/Provider.kt
app/src/main/java/com/tanasi/streamflix/providers/SerienStreamProvider.kt
app/src/main/java/com/tanasi/streamflix/ui/GlideCustomModule.kt
app/src/main/java/com/tanasi/streamflix/utils/AADecoder.java
app/src/main/res/layout/content_category_swiper_mobile.xml
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
navigation/build.gradle

Hi! Hope you had a great vacation.
- New german provider
- Two matching extractors
- Add dns resolver to glide image loader
- Reformated some of my old code
- Made the slideshow preview height a bit smaller on mobile
- update all dependencies
- add optional okhttp debugger dependency

feat: new german provider, image dns, dependencies update

---

app/src/main/java/com/tanasi/streamflix/providers/AnimeWorldProvider.kt

Hi, I fixed the AnimeWorld provider. I have never programmed in Kotlin or used Retrofit before, so I hope everything is correct 😄

fix animeworld provider

---

app/src/main/res/values-ar/strings.xml

I have added arabic language by added the arabic localizations for UI

added arabic

---

app/src/main/java/com/tanasi/streamflix/extractors/VixcloudExtractor.kt

Hi I fixed vixcloud extractor. Now all movies can be played.

fix vixcloud extractor

---

app/src/main/java/com/tanasi/streamflix/extractors/VixcloudExtractor.kt

Hi, I noticed that after making some edits, some movies started working again, but others didn’t. I’ve now tested several movies and series, and everything should be working fine. Sorry for the repeated PR.

fix-vixcloud-extractor

---

app/src/main/res/values-it/strings.xml

Added translation of menus into Italian. Hope this will help

Added Italian

---

app/build.gradle
app/src/main/java/com/tanasi/streamflix/extractors/Extractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/VidPlyExtractor.kt

Hi, I have added VidPly.com (DbStream) extractor
Tested on (_and more_): 
[Reacher S3 ep: (vf: 4,5) (vostfr: 4,5)](https://wiflix-pro.mom/serie-en-streaming/32858-reacher-saison-3.html)
[Shogun S1 all eps](https://wiflix-pro.mom/serie-en-streaming/29960-shogun-saison-1.html)
[The Brutalist](https://wiflix-pro.mom/film-en-streaming/32837-the-brutalist.html)

feat: add VidPly extractor

---

app/src/main/java/com/tanasi/streamflix/providers/FrenchAnimeProvider.kt
app/src/main/java/com/tanasi/streamflix/providers/Provider.kt

Hi, I have added [FrenchAnime](https://french-anime.com) provider

feat: add FrenchAnime provider

---

app/src/main/java/com/tanasi/streamflix/providers/FrenchAnimeProvider.kt

Fix to title to display "(FR) ..." If video is french
Before:
Solo Leveling
After: 
(FR) Solo Leveling

fix(FrenchAnimeProvider): fix title to display language

---

app/src/main/java/com/tanasi/streamflix/extractors/Extractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/MagaSavorExtractor.kt

Tested on:
[wiflix Daredevil: Born Again](https://wiflix-pro.mom/serie-en-streaming/32957-daredevil-born-again.html)
[french-anime solo leveling](https://french-anime.com/exclue/1592-solo-leveling.html)

feat(extractor): add MagaSavor extractor

---

app/src/main/java/com/tanasi/streamflix/extractors/Extractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/VidMoLyExtractor.kt

Tested on: [french-anime sakamoto days](https://french-anime.com/animes-vf/1623-sakamoto-days.html)

feat(extractor): add VidMoLy extractor

---

app/src/main/java/com/tanasi/streamflix/extractors/Extractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/VideoSibNet.kt

Tested on: [french-anime naruto shippuden](https://french-anime.com/exclue/39-naruto-shippuden-french.html)

feat(extractor): add VideoSibNet extractor

---

app/src/main/java/com/tanasi/streamflix/providers/StreamingCommunityProvider.kt

Piracyshield blocking .airforce domain in Italy

Update new StreamingCommunity domain

---

app/src/main/java/com/tanasi/streamflix/providers/StreamingCommunityProvider.kt

fix: updated endpoint and specify offset for getGenre

---

app/src/main/java/com/tanasi/streamflix/extractors/MagaSavorExtractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/VoeExtractor.kt
app/src/main/java/com/tanasi/streamflix/utils/DecryptHelper.kt

Create DecryptHelper object since MagaSavor and Voe have the same encoding for it's m3u8 links.
Moved the decrypt logic and findEncodedRegex logic into DecryptHelper object.
Voe Servers should now work in WiflixProvider.
thanks to @Max1Don for the decryption functions

Wiflixprovider fix

---

app/src/main/java/com/tanasi/streamflix/providers/StreamingCommunityProvider.kt

I _said_ I would take a break, but it broke!!
Website now supports english, but in my tests audio track still defaults to italian (you can test just by changing `lang` to `"en"`).
Closes #368

fix(streamingcommunity): updated endpoints and specify locale

---

app/src/main/java/com/tanasi/streamflix/providers/StreamingCommunityProvider.kt

fix(streamingcommunity): checks recommendations empty

---

app/src/main/java/com/tanasi/streamflix/providers/RidomoviesProvider.kt

add open dns and headers for requests to avoid error 403

Rido movies fix

---

app/src/main/java/com/tanasi/streamflix/database/dao/EpisodeDao.kt
app/src/main/java/com/tanasi/streamflix/extractors/BigWarpExtractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/Extractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/SaveFilesExtractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/VidozaExtractor.kt
app/src/main/java/com/tanasi/streamflix/providers/FilmPalastProvider.kt
app/src/main/java/com/tanasi/streamflix/providers/Provider.kt
app/src/main/java/com/tanasi/streamflix/ui/ShowOptionsMobileDialog.kt
app/src/main/java/com/tanasi/streamflix/ui/ShowOptionsTvDialog.kt
app/src/main/res/layout/dialog_show_options_mobile.xml
app/src/main/res/layout/dialog_show_options_tv.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml

added filmpalast provider (only movies for now)
added bigwarp and savefiles extractors
mark episodes till select as watched/unwatched
bigwarp is mp4, the encoding of the audio is ACC which for me is not working with exoplayer hence the ("VLC Only") tag

Filmpalast plus seen

---

app/src/main/java/com/tanasi/streamflix/extractors/DoodLaExtractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/Extractor.kt

added new url for doodstream

---

app/src/main/mobile/AndroidManifest.xml
app/src/main/tv/AndroidManifest.xml

update manifests for mobile and tv adding .StreamFlixApp as application name (i don't really understand why are those files not beeing shown in android studio, hence why they where not updated correctly)

Manifest update

---

app/src/main/java/com/tanasi/streamflix/extractors/MStreamClickExtractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/MStreamDayExtractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/MoflixExtractor.kt
app/src/main/java/com/tanasi/streamflix/extractors/VoeExtractor.kt
app/src/main/java/com/tanasi/streamflix/providers/FilmPalastProvider.kt
app/src/main/java/com/tanasi/streamflix/utils/AADecoder.java

fixed MoflixExtractor.kt, MStreamClickExtractor.kt, MStreamDayExtractor.kt and VoeExtractor.kt
changed the home from FilmPalastProvider.kt to page 1 of movies (still not going to add series, it's a WIP) added easier decode function in AADecoder.java

Minor Extractors fixes

---

app/src/main/java/com/tanasi/streamflix/database/AniWorldDatabase.kt
app/src/main/java/com/tanasi/streamflix/database/AppDatabase.kt
app/src/main/java/com/tanasi/streamflix/database/SerienStreamDatabase.kt
app/src/main/java/com/tanasi/streamflix/fragments/settings/SettingsMobileFragment.kt
app/src/main/java/com/tanasi/streamflix/fragments/settings/SettingsTvFragment.kt
app/src/main/java/com/tanasi/streamflix/providers/StreamingCommunityProvider.kt
app/src/main/java/com/tanasi/streamflix/utils/UserPreferences.kt
app/src/main/res/values/doh_resources.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings_mobile.xml
app/src/main/res/xml/settings_tv.xml
build.gradle

Aggiunta lista di selezione dns, e impostazioni separate per provider ( vedi streaming community )

Aggiunta lista di selezione dns, e impostazioni separate per provider 

---

app/src/main/java/com/tanasi/streamflix/fragments/settings/SettingsTvFragment.kt
app/src/main/res/xml/settings_mobile.xml
app/src/main/res/xml/settings_tv.xml
build.gradle

Fixed settings in mobile and TV

Fixed settings in mobile and TV

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/tanasi/streamflix/adapters/viewholders/MovieViewHolder.kt
app/src/main/java/com/tanasi/streamflix/adapters/viewholders/TvShowViewHolder.kt
app/src/main/res/values-it/strings.xml
app/src/main/res/values/strings.xml
build.gradle

Possibilità di scelta tra smarttube o youtube per visualizzare i trailer

Add SmartTube Support For 'Trailer' option
